// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Generates a fresh puzzle (random seed) and replaces the current game. */
	newGame: (spec: PuzzleSpec) => typedError<GameSnapshot, AppError>(__TAURI_INVOKE("new_game", { spec })),
	/**  The game restored on launch or started since, if any. */
	currentGame: () => typedError<{
	spec: PuzzleSpec,
	seed: number,
	rows: number,
	cols: number,
	cells: Cell[],
	entries: number[],
	marks: number[],
	conflicts: boolean[],
	solved: boolean,
} | null, AppError>(__TAURI_INVOKE("current_game")),
	setEntry: (index: number, digit: number) => typedError<GameSnapshot, AppError>(__TAURI_INVOKE("set_entry", { index, digit })),
	toggleMark: (index: number, digit: number) => typedError<GameSnapshot, AppError>(__TAURI_INVOKE("toggle_mark", { index, digit })),
	clearCell: (index: number) => typedError<GameSnapshot, AppError>(__TAURI_INVOKE("clear_cell", { index })),
};

/* Types */
/**
 *  Application-wide error type, also used at the IPC boundary.
 * 
 *  Serialized to the frontend as `{ kind, message? }`.
 */
export type AppError = { kind: "NoGame" } | { kind: "InvalidInput"; message: string } | { kind: "Io"; message: string } | { kind: "Internal"; message: string };

export type Cell = { kind: "White" } | 
/**  `down`: sum of the run below; `right`: sum of the run to the right. */
{ kind: "Block"; down: number | null; right: number | null };

/**  Everything the frontend renders. Never contains the solution. */
export type GameSnapshot = {
	spec: PuzzleSpec,
	seed: number,
	rows: number,
	cols: number,
	cells: Cell[],
	entries: number[],
	marks: number[],
	conflicts: boolean[],
	solved: boolean,
};

/**  Requested puzzle size. */
export type PuzzleSpec = { kind: "Beginner" } | { kind: "Intermediate" } | { kind: "Expert" } | { kind: "Custom"; rows: number; cols: number };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

